services:
  agent:
    build:
      context: ./Agent
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./Agent:/app/Agent
    command: jupyter lab --ip=0.0.0.0 --port 8888 --no-browser --allow-root
